---
title: "p8105_mtp_tt2714"
author: "Tiffany Tu"    
date: "10/18/2018"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(rvest)
library(ggplot2)
library(ggrepel)
library(kableExtra)
library(gridExtra)
```

```{r message=FALSE}
data = read_csv(file = "data/p8105_mtp_data.csv") 
clean_data = data %>% 
  gather(variable, value, -(week:day)) %>% 
  unite(temp, day) %>% rename(day = temp, time = variable, activity = value) %>% 
  mutate(time = str_replace(time, "activity\\.", "")) %>% 
  mutate(time = as.numeric(time), week = as.factor(week), 
         day = forcats::fct_relevel(day, c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'))) 
```

This dataset observes `r length(unique(clean_data$week))` weeks of recorded physical activity. 
--------------------------------------------

```{r activity distribution -day}
activity_day = clean_data %>% 
  group_by(week, day) %>% select(-time) %>% 
  summarise_all(funs(sum)) 

dist_dayplot = ggplot(activity_day, aes(x = day, y = activity)) + 
  geom_violin(adjust = 0.8, aes(fill = day)) + geom_boxplot(width = 0.1) + 
  labs(title = "Activity distribution on each day", x = "day of the week", y = "Activity (per Minute)") +
  theme_bw() + scale_y_continuous(labels = scales::comma)
```

```{r activity distribution - time}
time_formatter <- function(x) {h <- floor(x/60)}
activity_time = clean_data %>% 
  group_by(time, day) %>% select(-week) %>%
  summarise_all(funs(sum)) 

dist_timeplot = ggplot(activity_time, aes(x = time, y = activity, color = day)) + 
  geom_smooth(method = "auto") + 
  scale_x_continuous(label = time_formatter, breaks = seq(1, 1440, by = 64)) + 
  labs(title = "Activity distribution over 24 hour period", x = "Hour of the day", 
       y = "Activity (per Minute)") + theme_bw()
```

```{r message=FALSE}
grid.arrange(dist_timeplot, dist_dayplot)
```

```{r average activity per week (1-47)}
ggplot(clean_data %>% group_by(week) %>% select(-time, -day) %>% summarise_all(funs(sum)),
       aes(x = week, y = activity, group = 1, color = "red")) + 
  geom_point() + geom_line() + theme_bw() + scale_x_discrete(breaks = seq(1, 47, by = 4)) +
  scale_y_continuous(breaks = seq(0, 5000000, by = 500000)) + 
  labs(title = "Average activity per week", x = "Week", y = "Activity (per Minute)") +
  theme(legend.position = "none")
```

```{r week - activity over days}
week_analysis = clean_data %>% 
  filter(week == 1 | week == 15 | week == 30 | week == 47) 

week_plot1 = ggplot(week_analysis %>% select(-time) %>% 
  group_by(day, week) %>% summarise_all(funs(sum)), 
  aes(x = day, y = activity, group = week, color = week)) + 
  geom_point() + geom_line() + theme_bw() + 
  labs(title = "Average activity per day", x = "Day of the week", y = "Activity (per Minute)") 
```

```{r week - distribution of activity over time}
week_plot2 = ggplot(week_analysis %>% select(-day) %>% 
  group_by(time, week) %>% summarise_all(funs(sum)), 
  aes(x = time, y = activity, group = week, color = week)) + geom_smooth(method = "auto") + theme_bw() +
  labs(title = "Week distribution of activity", x = "Time (hours)", y = "Activity (per Minute)") + 
  scale_x_continuous(label = time_formatter, breaks = seq(1, 1440, by = 64))
```

```{r message=FALSE}
grid.arrange(week_plot1, week_plot2)
```

